version: '3.9'

services:
  load_balancer:
    build: ./load_balancer
    container_name: load_balancer_main
    ports:
      - "5001:5001"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    privileged: true
    networks:
      net1:
        aliases:
          - lb

networks:
  net1:
    external: true

